ALTER TABLE PRODUCT
	DROP
		CONSTRAINT FK_FOODTRUCK_TO_PRODUCT
		CASCADE;

ALTER TABLE FOODTRUCK
	DROP
		CONSTRAINT FK_LICENSE_NO_TO_FOODTRUCK
		CASCADE;

ALTER TABLE ORDERS
	DROP
		CONSTRAINT FK_MEMBER_TO_ORDERS
		CASCADE;

ALTER TABLE DELIVERYDETAIL
	DROP
		CONSTRAINT FK_ORDERS_TO_DELIVERYDETAIL
		CASCADE;

ALTER TABLE ORDERDETAIL
	DROP
		CONSTRAINT FK_PRODUCT_TO_ORDERDETAIL
		CASCADE;

ALTER TABLE ORDERDETAIL
	DROP
		CONSTRAINT FK_ORDERS_TO_ORDERDETAIL
		CASCADE;

ALTER TABLE LICENSE_NO
	DROP
		CONSTRAINT FK_SELLER_TO_LICENSE_NO
		CASCADE;

ALTER TABLE ORDERS
	DROP
		CONSTRAINT CK_ORDERS
		CASCADE;

ALTER TABLE SELLER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE PRODUCT
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE MEMBER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE FOODTRUCK
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE ORDERS
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE DELIVERYDETAIL
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE ADMIN
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE ORDERDETAIL
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE LICENSE_NO
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

/* 판매자 */
DROP TABLE SELLER 
	CASCADE CONSTRAINTS;

/* 제품 */
DROP TABLE PRODUCT 
	CASCADE CONSTRAINTS;

/* 회원 */
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

/* 푸드트럭 */
DROP TABLE FOODTRUCK 
	CASCADE CONSTRAINTS;

/* 주문 */
DROP TABLE ORDERS 
	CASCADE CONSTRAINTS;

/* 배달상세 */
DROP TABLE DELIVERYDETAIL 
	CASCADE CONSTRAINTS;

/* 관리자 */
DROP TABLE ADMIN 
	CASCADE CONSTRAINTS;

/* 주문상세 */
DROP TABLE ORDERDETAIL 
	CASCADE CONSTRAINTS;

/* 사업자번호 */
DROP TABLE LICENSE_NO 
	CASCADE CONSTRAINTS;

/* 판매자 */
CREATE TABLE SELLER (
	SEL_ID VARCHAR2(15) NOT NULL, /* 판매자아이디 */
	SEL_PW VARCHAR2(20) NOT NULL, /* 판매자비밀번호 */
	SEL_NAME VARCHAR2(15) NOT NULL, /* 판매자이름 */
	SEL_TEL VARCHAR2(14) NOT NULL /* 판매자연락처 */
);

ALTER TABLE SELLER
	ADD
		CONSTRAINT PK_SELLER
		PRIMARY KEY (
			SEL_ID
		);

/* 제품 */
CREATE TABLE PRODUCT (
	PROD_NO VARCHAR2(10) NOT NULL, /* 제품번호 */
	PROD_NAME VARCHAR2(100) NOT NULL, /* 제품이름 */
	PROD_CONTENT VARCHAR2(255), /* 제품내용 */
	PROD_PRICE NUMBER NOT NULL, /* 제품가격 */
	LICENSE_NO VARCHAR2(10) /* 사업자번호 */
);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT PK_PRODUCT
		PRIMARY KEY (
			PROD_NO
		);

/* 회원 */
CREATE TABLE MEMBER (
	MEM_ID VARCHAR2(15) NOT NULL, /* 회원아이디 */
	MEM_PW VARCHAR2(20) NOT NULL, /* 회원비밀번호 */
	MEM_NAME VARCHAR2(15) NOT NULL, /* 회원이름 */
	MEM_TEL VARCHAR2(14) NOT NULL /* 회원연락처 */
);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			MEM_ID
		);

/* 푸드트럭 */
CREATE TABLE FOODTRUCK (
	LICENSE_NO VARCHAR2(10) NOT NULL, /* 사업자번호 */
	FTRUCK_NAME VARCHAR2(80) NOT NULL, /* 푸드트럭이름 */
	FTRUCK_TEL VARCHAR2(14) NOT NULL, /* 푸드트럭연락처 */
	FTRUCK_ADDR VARCHAR2(100), /* 푸드트럭주소 */
	FTRUCK_DLV_YN CHAR(1) DEFAULT 'N', /* 푸드트럭배달여부 */
	FTRUCK_RSV_YN CHAR(1) DEFAULT 'N', /* 푸드트럭예약여부 */
	FTRUCK_STATE CHAR(1) DEFAULT 'N' NOT NULL, /* 영업상태 */
	FTRUCK_GRADE NUMBER(2,1) DEFAULT 0 NOT NULL, /* 평점 */
	FTRUCK_IMG VARCHAR2(255), /* 푸드트럭이미지 */
	LATITUDE VARCHAR2(255), /* 위도 */
	LONGITUDE VARCHAR2(255) /* 경도 */
);

ALTER TABLE FOODTRUCK
	ADD
		CONSTRAINT PK_FOODTRUCK
		PRIMARY KEY (
			LICENSE_NO
		);

/* 주문 */
CREATE TABLE ORDERS (
	ORDER_NO NUMBER(15) NOT NULL, /* 주문번호 */
	ORD_NAME VARCHAR2(15) NOT NULL, /* 주문자이름 */
	ORD_TEL VARCHAR2(14) NOT NULL, /* 주문자연락처 */
	ORD_DATE DATE DEFAULT SYSDATE NOT NULL, /* 주문시간 */
	ORD_RSV_DATE DATE NOT NULL, /* 예약시간 */
	ORD_DLV_YN CHAR(1) DEFAULT 'N', /* 배달여부 */
	MEM_ID VARCHAR2(15) /* 회원아이디 */
);

ALTER TABLE ORDERS
	ADD
		CONSTRAINT PK_ORDERS
		PRIMARY KEY (
			ORDER_NO
		);

ALTER TABLE ORDERS
	ADD
		CONSTRAINT CK_ORDERS
		CHECK (<지정 되지 않음>);

/* 배달상세 */
CREATE TABLE DELIVERYDETAIL (
	ORDER_NO NUMBER(15) NOT NULL, /* 주문번호 */
	DLV_STATE NUMBER(1) DEFAULT 0 NOT NULL, /* 배달상태 */
	DLV_ADDR VARCHAR2(100) NOT NULL, /* 배달주소 */
	DLV_DATE DATE NOT NULL /* 배달시간 */
);

ALTER TABLE DELIVERYDETAIL
	ADD
		CONSTRAINT PK_DELIVERYDETAIL
		PRIMARY KEY (
			ORDER_NO
		);

/* 관리자 */
CREATE TABLE ADMIN (
	ADMIN_ID VARCHAR2(15) NOT NULL, /* 관리자아이디 */
	ADMIN_PW VARCHAR2(20) NOT NULL, /* 관리자비밀번호 */
	ADMIN_TEL VARCHAR2(14) NOT NULL /* 관리자연락처 */
);

ALTER TABLE ADMIN
	ADD
		CONSTRAINT PK_ADMIN
		PRIMARY KEY (
			ADMIN_ID
		);

/* 주문상세 */
CREATE TABLE ORDERDETAIL (
	PROD_NO VARCHAR2(10) NOT NULL, /* 제품번호 */
	ORDER_NO NUMBER(15) NOT NULL, /* 주문번호 */
	QTY NUMBER DEFAULT 1 NOT NULL, /* 수량 */
	ORD_PRICE NUMBER NOT NULL /* 주문가격 */
);

ALTER TABLE ORDERDETAIL
	ADD
		CONSTRAINT PK_ORDERDETAIL
		PRIMARY KEY (
			PROD_NO,
			ORDER_NO
		);

/* 사업자번호 */
CREATE TABLE LICENSE_NO (
	LICENSE_NO VARCHAR2(10) NOT NULL, /* 사업자번호 */
	SEL_ID VARCHAR2(15) NOT NULL /* 판매자아이디 */
);

ALTER TABLE LICENSE_NO
	ADD
		CONSTRAINT PK_LICENSE_NO
		PRIMARY KEY (
			LICENSE_NO
		);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT FK_FOODTRUCK_TO_PRODUCT
		FOREIGN KEY (
			LICENSE_NO
		)
		REFERENCES FOODTRUCK (
			LICENSE_NO
		);

ALTER TABLE FOODTRUCK
	ADD
		CONSTRAINT FK_LICENSE_NO_TO_FOODTRUCK
		FOREIGN KEY (
			LICENSE_NO
		)
		REFERENCES LICENSE_NO (
			LICENSE_NO
		);

ALTER TABLE ORDERS
	ADD
		CONSTRAINT FK_MEMBER_TO_ORDERS
		FOREIGN KEY (
			MEM_ID
		)
		REFERENCES MEMBER (
			MEM_ID
		);

ALTER TABLE DELIVERYDETAIL
	ADD
		CONSTRAINT FK_ORDERS_TO_DELIVERYDETAIL
		FOREIGN KEY (
			ORDER_NO
		)
		REFERENCES ORDERS (
			ORDER_NO
		);

ALTER TABLE ORDERDETAIL
	ADD
		CONSTRAINT FK_PRODUCT_TO_ORDERDETAIL
		FOREIGN KEY (
			PROD_NO
		)
		REFERENCES PRODUCT (
			PROD_NO
		);

ALTER TABLE ORDERDETAIL
	ADD
		CONSTRAINT FK_ORDERS_TO_ORDERDETAIL
		FOREIGN KEY (
			ORDER_NO
		)
		REFERENCES ORDERS (
			ORDER_NO
		);

ALTER TABLE LICENSE_NO
	ADD
		CONSTRAINT FK_SELLER_TO_LICENSE_NO
		FOREIGN KEY (
			SEL_ID
		)
		REFERENCES SELLER (
			SEL_ID
		);